sudo ../flow_table/simple_switch_CLI --thrift-port 9090 <../flow_table/flow_table/s1_s1.txt
sudo ../flow_table/simple_switch_CLI --thrift-port 9091 <../flow_table/flow_table/s1_s2.txt
sudo ../flow_table/simple_switch_CLI --thrift-port 9092 <../flow_table/flow_table/s2_s1.txt
sudo ../flow_table/simple_switch_CLI --thrift-port 9093 <../flow_table/flow_table/s2_s2.txt
sudo ../flow_table/simple_switch_CLI --thrift-port 9094 <../flow_table/flow_table/p1_l1.txt
sudo ../flow_table/simple_switch_CLI --thrift-port 9095 <../flow_table/flow_table/p1_l2.txt
sudo ../flow_table/simple_switch_CLI --thrift-port 9096 <../flow_table/flow_table/p2_l1.txt
sudo ../flow_table/simple_switch_CLI --thrift-port 9097 <../flow_table/flow_table/p2_l2.txt
sudo ../flow_table/simple_switch_CLI --thrift-port 9098 <../flow_table/flow_table/p1_t1.txt
sudo ../flow_table/simple_switch_CLI --thrift-port 9099 <../flow_table/flow_table/p1_t2.txt
sudo ../flow_table/simple_switch_CLI --thrift-port 9100 <../flow_table/flow_table/p2_t1.txt
sudo ../flow_table/simple_switch_CLI --thrift-port 9101 <../flow_table/flow_table/p2_t2.txt
